// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gin-gonic/gin"
	"secret-management/internal/handler"
	"secret-management/internal/usecase"
)

// Injectors from wire.go:

func InitializeDependency(router *gin.RouterGroup) (*Handlers, error) {
	healthHandler := handler.NewHealthHandler(router)
	secretUsecase := usecase.NewSecretUsecase()
	secretHandler := handler.NewSecretHandler(router, secretUsecase)
	handlers := &Handlers{
		HealthHandler: healthHandler,
		SecretHandler: secretHandler,
	}
	return handlers, nil
}

// wire.go:

type Handlers struct {
	HealthHandler *handler.HealthHandler
	SecretHandler *handler.SecretHandler
}
